### ISSUE TITLE
Impression

### ISSUE THREAD

**Issue by corentinmb** [MAIF/cards#1]
Y aura-t-il la feature d'impression des cartes ? Histoire de pouvoir jouer avec de vraies cartes :-) ?

**Comment by gotson** [comment]
👍 
Apparently some decks were handed over at Devoxx, but it would definitely be good to be able to print, especially for people on the other side of the planet :)

**Comment by gotson** [comment]
I did some research about printing, and found a few things:

- when trying to print a webpage, a specific css for `media=print` is required
- i found out that the standard cards usually have a height of 3.5" (88.9mm). Depending on the card format the width can differ (poker cards are 2.5", bridge cards are a bit narrower).
- i tested a few websites when you can upload images to print cards, but the resolution of the provided `.png` files is too low. Ideally we would need higher resolution images.
- some online printing services require a multi-page `.pdf` file (with one one-sided card per page), while others accept `.png` or `.tiff` files

I'm not sure what would be the best approach to provide a printing facility for those cards.
Maybe a first step would be to have a dedicated `.css` for printing, that would remove the background (or provide a grey background, since the cards border is white), size the cards correctly to 3.5" height (keeping aspect ratio), and place cards in a way that when printing on A4 it's equally distributed on the page for easy cutting.

What do you think ?

**Comment by desmfr** [comment]
Hello

we work on it, we want to share the the file that we gave to the professional printer to make the real deck but it's not appropriate to classic home printers (the cards are recto/verso).

we are looking for an easy to print and cut solution ;)

**Comment by desmfr** [comment]
i assign this issue to our talended designer ;) @francois-4h04

**Comment by gotson** [comment]
@desmfr i would also be interested in the file for professional printer!

**Comment by baudelotphilippe** [comment]
I published a new version with a print feature.
Borders are display around the cards and 1 double-sided card / page.
It's better to print in landscape mode.

Looking for your feedbacks

**Comment by gotson** [comment]
> I published a new version with a print feature.
> Borders are display around the cards and 1 double-sided card / page.
> It's better to print in landscape mode.
> 
> Looking for your feedbacks

Since the hosted version on GH pages is not updated i built a local one to check the changes, but when i try to print or emulate print using Chrome 70 i still get white background on the cards.

**Comment by baudelotphilippe** [comment]
Have you launch the generator ?

**How to**
yarn install
yarn generator (build the cards)
yarn server
Launch : http://localhost:3000/cards/

**Comment by gotson** [comment]
@baudelotphilippe yes i did, that's the rendering i get with media `print`.

![image](https://user-images.githubusercontent.com/2139133/50957184-8b1eb080-14f8-11e9-8dc9-b2d8dba1a882.png)

**Comment by baudelotphilippe** [comment]
yes, it's correct.

it's printable like that, no ?

**Comment by gotson** [comment]
oh ok, in my mind the idea was to print it like real cards with the colors and borders :)

**Comment by mathieuancelin** [comment]
Hello all,

I've just added a new generator phase to create pdfs (yarn pdf) from cards. It's not perfect yet, but we're close ;)

* https://maif.github.io/cards/pdfs/cards-ar.pdf
* https://maif.github.io/cards/pdfs/cards-de.pdf
* https://maif.github.io/cards/pdfs/cards-en.pdf
* https://maif.github.io/cards/pdfs/cards-es.pdf
* https://maif.github.io/cards/pdfs/cards-fr.pdf
* https://maif.github.io/cards/pdfs/cards-ja.pdf
* https://maif.github.io/cards/pdfs/cards-ru.pdf
* https://maif.github.io/cards/pdfs/cards-zh-CN.pdf

**Comment by desmfr** [comment]
original fr file available in the repo
https://github.com/MAIF/cards/raw/master/pdf/cards.pdf
